### ISSUE TITLE
Beware the pre-installed tools (especially newer/other python versions)

### ISSUE THREAD

**Issue by AleksandraLaura** [antonisdim/haystac#19]
Hi! 👋
_(I have left the same issue on the_ [_haystac_paper_](https://github.com/antonisdim/haystac_paper) _GitHub before realizing that this is the place to put it instead)._ 
I have noticed that many people have issues with running HAYSTAC due to other python version interfering with the one in the conda environment that should be used (Python v3.6.7). The error message doesn't state this issue very clearly (that the python version has to be exactly 3.6.7) and I would suggest this was documented somewhere in the ReadMe.md or a clear error message could be implemented.
Thanks!

**Comment by antonisdim** [comment]
Hello Aleksandra, 

I hope you are doing great and apologies for not getting back to you earlier !

Thank you for your suggestion, that is true something like that could happen. Currently we suggest users install ``haystac`` by creating a separate ``conda`` environment so that all the necessary dependencies are installed correctly (including the correct ``python`` version). 

But you are absolutely right that we can communicate discrepancies like these to the end-user more clearly, and in the future we'll try to implement a more explicit approach as you suggested. 

Thank you for your feedback, and please let us know if anything else catches your eye !

Best, 
Antony

**Comment by AleksandraLaura** [comment]
Hi Antony, 

Thank you for the nice reply, absolutely no apologies needed! 

I'm aware of the installation recommendations, and from my experience everything works absolutely as it should. I should have perhaps been more clearly on the issue I've encountered: 
I think it would be very beneficial to the user (especially an inexperienced one) to write somewhere in the installation guidelines that it is very important that no other tools can be interfering with the ones in the `conda` environment. I think the higher `python` versions may be overwriting the one within the installed environment, but I'm not sure if it's exactly this causing the issue. The only thing I know is that this had been the main source of confusion from multiple of colleagues, completely independently of each other. I think it's a pity because I find `haystac` to work really well. 

I hope this clarifies my comment a little bit. 

Best,
Aleksandra
